name: Release

on:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup 
        with:
          go-version: '1.24'

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Check Go formatting
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi
      - name: Build
        run: |
          go mod tidy 
          make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: make test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Latest Tag
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Update README Tag
        run: |
          sed -i "s/<LATEST_TAG>/${LATEST_TAG}/g" README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README Release Tag to $LATEST_TAG"
          git push
